version: '3.8'

services:
  db:
    image: postgres:17
    container_name: db_normalizacion
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: normalizacion_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/ddl:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: app_normalizacion
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pgdata: